version: '3.8'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: estapar
      POSTGRES_USER: estapar
      POSTGRES_PASSWORD: estapar
    ports:
      - "5430:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: estapar-springboot-app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/estapar
      SPRING_DATASOURCE_USERNAME: estapar
      SPRING_DATASOURCE_PASSWORD: estapar
    ports:
      - "8080:8080"

volumes:
  db_data: