spring:
  application:
    name: estapar
    mvc:
      pathmatch:
        matching-strategy: ant_path_matcher
    springdoc:
      api-docs:
        path: /v3/api-docs
      swagger-ui:
        path: /swagger-ui.html
  datasource:
    url: jdbc:postgresql://localhost:5430/estapar
    username: estapar
    password: estapar
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect




